opacity according to number of voters
JanVan01/ReferendumMapMuenster pull request #13
Opened 2017-01-21 15:55 UTC by salman-kh

2017-01-21 16:02 UTC, JanVan01 requested changes

2017-01-21 16:02 UTC, JanVan01 commented on index.html
> +body{
Should be in the style.css file

2017-01-21 16:02 UTC, JanVan01 commented on js/data.js
> +       fillOpacity: getOpacity(feature.properties.totalVoters)
Opacity should be based on the fraction of people that voted. So it should be something like: (yes+no)/totalVoters

2017-01-21 16:02 UTC, JanVan01 commented on js/data.js
> +function getOpacity(voters) {
See comment above. If we already have a fraction, we can just set the opacity as that fraction.

2017-01-22 19:16 UTC, JanVan01 approved these changes

2017-01-22 20:47 UTC, salman-kh reviewed
Looks good

2017-01-22 20:47 UTC, merged